baseurl: /SecondaryCities
permalink: /:categories/:title

defaults:
  -
    scope:
      path: _posts/en
    values:
      lang: English
  -
    scope:
      path: _posts/es
    values:
      lang: Español
